[package]
name = "io-uring-zcrx"
version = "0.1.0"
edition = "2021"
license = "MIT"

[dependencies]
io-uring = { git = "https://github.com/beviu/io-uring.git", branch = "zcrx" }
libc = { version = "0.2", default-features = false }
